name: Report bug
description: Report a bug found
title: "bug: "
labels: ["bug", "ui"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please fill out the following details so we can respond and act efficiently.

  - type: textarea
    attributes:
      label: Bug description
      description: Describe roughly what the bug is. For interface issues, please include relevant screenshots or recordings.
      placeholder: |
        Example: "Widgets underneath the top bar"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide an example of how to replicate the bug.
      placeholder: |
        Example:
        1. Click here
        2. Click That
        3. Put this here
        4. And etc
    validations:
      required: true

  - type: textarea
    attributes:
      label: Primary pain point(s)
      description: What is this bug actively stopping you from doing? This is helpful for us to suggest temporary workarounds while the actual issue is being fixed.
      placeholder: |
        Example: "When the widget is obstructed I can't see the information I need."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: System logs, links to relevant forum discussions, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following (and check the boxes) before submitting.
      options:
        - label: I have checked to make sure that a similar request has not already been filed or fixed.
          required: true
