/**
 * What the bundled Piper voices are given in place of the capitalized words that show up in alerts, keyed by the
 * exact run of letters in the text. Piper guesses whether a run of capitals is a word or an acronym, and guesses
 * differently from one sentence to the next ("EKF bad" comes out as "F bad"), so every acronym is listed, spelled out
 * unless it reads better as a word or expanded (UART, NED), along with the words it misreads or that read better
 * expanded (ALT, THR). Capitalized words it reads right, like AUTO or FAILED, are left out.
 *
 * Built from every text message ArduPilot sends to the ground station, parameter names included. Add an entry when
 * an alert reads wrong.
 */
export const pronunciations: ReadonlyMap<string, string> = new Map(
  Object.entries({
    AC: 'A.C.',
    ACC: 'accel',
    ACK: 'ack',
    ACRO: 'acro',
    ADSB: 'A.D.S.B.',
    AFS: 'A.F.S.',
    AHRS: 'A.H.R.S.',
    ALT: 'altitude',
    ALTERR: 'altitude error',
    AMSL: 'A.M.S.L.',
    ANG: 'angle',
    ANX: 'A.N.X.',
    AP: 'A.P.',
    APM: 'A.P.M.',
    ARM: 'arm',
    AROT: 'autorotation',
    AS: 'A.S.',
    AUAV: 'A.U.A.V.',
    AUTOLAND: 'auto land',
    AXIS: 'axis',
    BAL: 'balance',
    BANG: 'bang',
    BARO: 'baro',
    BAT: 'battery',
    BATT: 'battery',
    BBR: 'B.B.R.',
    BC: 'B.C.',
    BTN: 'button',
    BV: 'B.V.',
    CAL: 'calibration',
    CAM: 'cam',
    CAMERA: 'camera',
    CAN: 'can:',
    CANManager: 'can: manager',
    CFG: 'C.F.G.',
    CLASS: 'class',
    CMUX: 'C.M.U.X.',
    COL: 'collective',
    COM: 'C.O.M.',
    COMPID: 'component I.D.',
    COUNT: 'count',
    CPU: 'C.P.U.',
    CRC: 'C.R.C.',
    CRSF: 'C.R.S.F.',
    DAT: 'D.A.T.',
    DB: 'D.B.',
    DDFP: 'D.D.F.P.',
    DDVP: 'D.D.V.P.',
    DEG: 'degrees',
    DEVID: 'device I.D.',
    DFU: 'D.F.U.',
    DIR: 'directory',
    DJIR: 'D.J.I.R.',
    DLA: 'D.L.A.',
    DMA: 'D.M.A.',
    DNA: 'D.N.A.',
    DOCK: 'dock',
    DR: 'D.R.',
    DroneCAN: 'drone can:',
    DSP: 'D.S.P.',
    EAHRS: 'external A.H.R.S.',
    EFI: 'E.F.I.',
    EK: 'E.K.',
    EKF: 'E.K.F.',
    ERROR: 'error',
    ESC: 'E.S.C.',
    ESCs: 'E.S.C.s',
    EXTD: 'extended',
    ExternalAHRS: 'external A.H.R.S.',
    FA: 'F.A.',
    FBWA: 'fly by wire A',
    FETtec: 'fet tech',
    FF: 'F.F.',
    FFT: 'F.F.T.',
    FICSR: 'F.I.C.S.R.',
    FL: 'F.L.',
    FLR: 'F.L.R.',
    FLTMODE: 'flight mode',
    FOLL: 'follow',
    FS: 'F.S.',
    FSM: 'F.S.M.',
    FT: 'F.T.',
    FTP: 'F.T.P.',
    FTW: 'F.T.W.',
    FW: 'F.W.',
    FWD: 'forward',
    FXSCALER: 'F X scaler',
    FYSCALER: 'F Y scaler',
    GCS: 'G.C.S.',
    GEN: 'generator',
    GNSS: 'G.N.S.S.',
    GPIO: 'G.P.I.O.',
    GPS: 'G.P.S.',
    GSF: 'G.S.F.',
    GSOF: 'G.S.O.F.',
    HAL: 'H.A.L.',
    HDOP: 'H.D.O.P.',
    HW: 'H.W.',
    ICAO: 'I.C.A.O.',
    ICEngine: 'I.C. engine',
    ID: 'I.D.',
    IDENT: 'ident',
    IE: 'I.E.',
    IEC: 'I.E.C.',
    ILAB: 'I lab',
    IMU: 'I.M.U.',
    IMUs: 'I.M.U.s',
    INF: 'info',
    INIT: 'init',
    INS: 'inertial navigation system',
    INT: 'int',
    IO: 'I.O.',
    IOMCU: 'I.O.M.C.U.',
    IP: 'I.P.',
    ISB: 'I.S.B.',
    ISR: 'I.S.R.',
    KDECAN: 'K.D.E. can:',
    KEBNI: 'K.E.B.N.I.',
    KHz: 'kilohertz',
    LAND: 'land',
    LAT: 'latitude',
    LATITUDE: 'latitude',
    LEDs: 'L.E.D.s',
    LEN: 'length',
    LH: 'L.H.',
    LIM: 'limit',
    LLH: 'L.L.H.',
    LOITER: 'loiter',
    LONGITUDE: 'longitude',
    LOSS: 'loss',
    LTC: 'L.T.C.',
    LTE: 'L.T.E.',
    MAG: 'M.A.G.',
    MAVFTP: 'mav F.T.P.',
    MAVn: 'mav N',
    MAX: 'max',
    MAXHZ: 'max hertz',
    MC: 'M.C.',
    MCAST: 'multicast',
    MCP: 'M.C.P.',
    MHz: 'megahertz',
    MIN: 'min',
    MM: 'M.M.',
    MS: 'M.S.',
    MSL: 'M.S.L.',
    MSP: 'M.S.P.',
    MT: 'M.T.',
    MV: 'M.V.',
    MXS: 'M.X.S.',
    MYGCS: 'my G.C.S.',
    NACK: 'nack',
    NavEKF: 'nav E.K.F.',
    NE: 'N.E.',
    NED: 'north east down',
    NET: 'net',
    NMEA: 'N.M.E.A.',
    NoGPS: 'no G.P.S.',
    NON: 'non',
    NTRIP: 'N trip',
    NWPMU: 'N.W.P.M.U.',
    OA: 'O.A.',
    ODID: 'O.D.I.D.',
    OFF: 'off',
    ONVIF: 'on vif',
    OPTIONS: 'options',
    ORIENT: 'orientation',
    OSD: 'on-screen display',
    PCM: 'P.C.M.',
    PHANG: 'phase angle',
    PiccoloCAN: 'piccolo can:',
    PIN: 'pin',
    PITCH: 'pitch',
    PLD: 'P.L.D.',
    PLDP: 'P.L.D.P.',
    PLND: 'precision landing',
    POI: 'P.O.I.',
    PORT: 'port',
    POS: 'position',
    POSXY: 'position X Y',
    POSZ: 'position Z',
    PPP: 'P.P.P.',
    PPPGW: 'P.P.P.G.W.',
    PPS: 'P.P.S.',
    ProfiLED: 'profi L.E.D.',
    PRX: 'P.R.X.',
    PT: 'P.T.',
    PTCH: 'pitch',
    PWM: 'P.W.M.',
    PWR: 'P.W.R.',
    QAssist: 'Q assist',
    QFwdThr: 'Q forward throttle',
    QUADPLANE: 'quadplane',
    RAMP: 'ramp',
    RAW: 'raw',
    RC: 'R.C.',
    RCIN: 'R.C. in',
    RF: 'R.F.',
    RK: 'R.K.',
    RNG: 'range',
    RNGFND: 'rangefinder',
    ROLL: 'roll',
    RPM: 'R.P.M.',
    RSC: 'R.S.C.',
    RSSI: 'R.S.S.I.',
    RTCM: 'R.T.C.M.',
    RTCMv: 'R.T.C.M. version',
    RTL: 'R.T.L.',
    RTun: 'rate tune',
    RUN: 'run',
    RUNCAM: 'run cam',
    RX: 'R.X.',
    SaveWP: 'save waypoint',
    SBF: 'S.B.F.',
    SBG: 'S.B.G.',
    SCHED: 'scheduler',
    SCR: 'scripting',
    SCRPORT: 'scripting port',
    SD: 'S.D.',
    SDP: 'S.D.P.',
    SensAItion: 'sensation',
    SERPORT: 'serial port',
    SERVOx: 'servo X',
    SET: 'set',
    SF: 'S.F.',
    SHT: 'S.H.T.',
    SID: 'S.I.D.',
    SIM: 'sim',
    SITL: 'S.I.T.L.',
    SL: 'S.L.',
    SLCAN: 'S.L. can:',
    SMDPT: 'S.M.D.P.T.',
    SMMTW: 'S.M.M.T.W.',
    SN: 'S.N.',
    SOAR: 'soar',
    SPACING: 'spacing',
    SPD: 'speed',
    SPIs: 'S.P.I.s',
    SRC: 'source',
    SToRM: 'storm',
    SVF: 'S.V.F.',
    SW: 'S.W.',
    TAIL: 'tail',
    TAILSIT: 'tailsitter',
    TAP: 'T.A.P.',
    TCAL: 'T.C.A.L.',
    TCP: 'T.C.P.',
    TERRN: 'terrain',
    TF: 'T.F.',
    TFMini: 'T.F. mini',
    TFS: 'T.F.S.',
    THR: 'throttle',
    TIx: 'T.I. X',
    TKOFF: 'takeoff',
    TN: 'T.N.',
    ToshibaLED: 'toshiba L.E.D.',
    TRMP: 'T.R.M.P.',
    TRMS: 'T.R.M.S.',
    TRQD: 'T.R.Q.D.',
    TRSE: 'T.R.S.E.',
    TRST: 'T.R.S.T.',
    TX: 'T.X.',
    UART: 'U art',
    UAS: 'U.A.S.',
    UC: 'U.C.',
    UDP: 'U.D.P.',
    UIH: 'U.I.H.',
    UM: 'U.M.',
    VALDEL: 'val del',
    VALGET: 'val get',
    VALSET: 'val set',
    VEL: 'velocity',
    VELXY: 'velocity X Y',
    VELZ: 'velocity Z',
    VISO: 'visual odometry',
    VM: 'V.M.',
    VNERR: 'V.N.E.R.R.',
    VTOL: 'vee tol',
    VTX: 'V.T.X.',
    WDG: 'W.D.G.',
    WEnc: 'wheel encoder',
    WMM: 'world magnetic model',
    WP: 'waypoint',
    XY: 'X.Y.',
    YAW: 'yaw',
  })
)
