name: Docs Check

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-if-docs-needed:
    if: contains(github.event.pull_request.labels.*.name, 'docs-needed')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR needs accompanying docs to be written
        run: |
          echo "This change needs to be documented. Please get the docs approved, and change 'docs-needed' to 'docs-complete'."
          exit 1
